pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=Ksisu
      - status-success=continuous-integration/travis-ci/pr
      - status-success=Tests CI / build (pull_request)
    actions:
      merge:
        method: squash
      label:
        add: [dependency-update]
