sudo: required

language: scala

branches:
  only:
    - master
    - /^v.*$/

services:
  - docker

script:
  - docker-compose -f docker-compose.travis.yml up -d
  - docker-compose -f docker-compose.travis.yml exec tutelar sbt -mem 2048 clean compile test it:test

before_deploy:
  - sudo chown -R $UID .
  - git config --global user.name "travis"
  - git config --global user.email "travis@tutelar"
  - openssl aes-256-cbc -K $encrypted_5b60a6c9b373_key -iv $encrypted_5b60a6c9b373_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key

deploy:
  provider: script
  script: sbt "; project docs ; makeSite ; ghpagesPushSite"
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v.*$"
