FROM hseeberger/scala-sbt:8u181_2.12.7_1.2.6

# resolve dependencies first (cache)
COPY build.sbt /app/build.sbt
COPY project /app/project
COPY .scalafmt.conf /app/.scalafmt.conf
WORKDIR /app
RUN sbt update test:update it:update

# build the application
COPY src /app/src
RUN sbt compile docker:stage