addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.1")
addSbtPlugin("au.com.onegeek"   %% "sbt-dotenv"         % "2.1.147")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.0.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.9.0")
