name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1

    steps:
      - uses: actions/checkout@v1
      - name: Compose up
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Compile & Test
        run: docker-compose -f docker-compose.ci.yml exec -T tutelar sbt --supershell=false -mem 2048 clean compile test it:test stage "; project docs ; makeSite"
      - name: Build docker image
        run: |
          cp -R ./target/universal/stage ./stage
          chmod -R u=rX,g=rX ./stage && chmod u+x,g+x ./stage/bin/tutelar
          docker build -t teamwanari/tutelar:latest .
      - name: Push To DockerHub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u teamwanari --password-stdin
          docker push teamwanari/tutelar:latest
